### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by thedjnK** [thedjnK/AuTerm#1]
Current planned tasks (not in priority order):

- [ ] Add a plugin system
- [ ] Refactor and improve speed test code
- [ ] VT100 formatting, perhaps supporting it, perhaps just stripping it and retaining monochrome
- [ ] Builds for linux and windows
- [ ] Split the 5000+ lines in UwxMainWindow into many, many other files
- [ ] Potential MCUmgr plugin/integration
