### ISSUE TITLE
MCUmgr plugin TODO list

### ISSUE THREAD

**Issue by thedjnK** [thedjnK/AuTerm#2]
- [x] Move to smp_message
- [x] Initial FS mgmt group functions
- [x] Initial IMG mgmt group functions
- [x] Initial OS mgmt group functions
- [x] Initial stats mgmt group functions
- [x] Initial shell mgmt group functions
- [x] Complete FS upload functionality
- [x] Complete FS download functionality
- [x] Complete FS hash functionality
- [x] Complete IMG upload functionality
- [x] Complete IMG image get/set functionality
- [x] Complete IMG erase functionality
- [x] Complete OS echo functionality
- [x] Complete OS stats functionality
- [x] Complete OS memory functionality
- [x] Complete OS reset functionality
- [x] Complete OS buffer info functionality
- [x] Complete OS uname functionality
- [x] Complete stats list groups functionality
- [x] Complete stats fetch stats functionality
- [x] Complete shell execute functionality
- [x] Message repeating
- [x] Timing out
- [x] Fix MTU for total packet size post-base64, not pre-base64
- [x] Initial UDP transport
- [x] Finish UDP transport
- [x] Initial Bluetooth transport
- [x] Finish Bluetooth transport
- [x] Check image header to determine image endianess (or error if not valid for either)

**Comment by thedjnK** [comment]
Complete in 0.34
